openapi: 3.0.1
info:
  title: ぽんしゅきー
  description: ぽんしゅきーサイトで使用するバックエンドAPI
  contact:
    email: javawoman.tokyo@gmail.com 
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: GitHubはこちら
  url: https://github.com/java-women/Ponsyukey
paths:
  /saketomo:
    post:
      summary: 会員登録API
      operationId: createSaketomo
      requestBody: 
        description: 会員登録に必要な情報
        content:
          application/json:
            schema: 
              properties:
                Saketomo:
                  type: object
                  properties:
                    name:
                      type: string
                    image:
                      type: string
                      description: 既存画像から選んでもらう(キーもしくはURL)。enumにない値もしくは空/nullの場合はバリデーションチェックでエラーにします
                      enum:
                      - icon1
                      - icon2
                      - icon3
                    auth:
                      type: object
                      properties:
                        password: 
                          type: string
                          format: password
                          description: ハッシュ
                        email:
                          type: string
                      required:
                        - password
                        - email
                  required: 
                    - name
        required: true
      responses:
        200:
          description: http ステータスコード 200 ok。バリデーションエラー時も200でレスポンスする
          content:
            application/json:
              schema: 
                properties:
                  resultCode:
                    type: string
                  Saketomo:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      name:
                        type: string
                      image:
                        type: string
                        enum:
                        - icon1
                        - icon2
                        - icon3
        400:
          description: http ステータスコード 400 error
        500:
          description: http ステータスコード 500 error


    
